### Get groups
GET http://localhost:8080/api/getAllGroupsMongo

### Save random group
GET http://localhost:8080/api/saveRandomGroup

###
GET http://localhost:8080/api/getAllStudentsRedis

###
POST http://localhost:8080/api/addStudent
Content-Type: application/json

{
  "id": "a32a9751-3b12-59ec-856c-a4c298462451",
  "name": "Dmitry"
}

###
POST http://localhost:8080/api/addLecture
Content-Type: application/json

{
  "id": "a30a8751-3b32-48fc-856c-a4c298462451",
  "name": "Math",
  "text": "Hello World"
}

###
GET http://localhost:8080/api/getLectures

###
POST http://localhost:8080/api/lab_1
Content-Type: application/json

{
  "lecturePhrase": "World"
}

###

GET http://localhost:8080/api/labOneData

###

POST http://localhost:8080/api/labOneQuery
Content-Type: application/json

{
  "lecturePhrase": "а",
  "from": "2021-01-01T00:00:00",
  "to": "2021-12-01T00:00:00",
  "number": 100
}

###

POST http://localhost:8080/api/labTwoQuery
Content-Type: application/json

{
  "semester": 2,
  "year": 2021
}

###

POST http://localhost:8080/api/labThreeQuery
Content-Type: application/json

{
  "groupId": "81D73E87",
  "number": 1000
}

###