version: '2'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/var/lib/mongo/data/

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - db_data:/var/lib/redis/data/
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - client.transport.sniff=true
    volumes:
      - db_data:/var/lib/elastic-search/data

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres

volumes:
  db_data: